# Generated by Django 5.2.13 on 2026-04-30 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('teams', '0002_player_avg_rating_player_matches_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Screenshot proof (mandatory for red cards)', null=True, upload_to='card_screenshots/'),
        ),
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, help_text='Match rating out of 10', max_digits=3)),
                ('screenshot', models.ImageField(help_text='Screenshot of in-game rating', upload_to='rating_screenshots/')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_ratings', to='teams.player')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='matches.matchresult')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ['-rating'],
                'unique_together': {('result', 'player')},
            },
        ),
    ]
