# Generated by Django 5.2.13 on 2026-05-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_card_screenshot_playerrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Full-time scoreline screenshot', null=True, upload_to='match_screenshots/'),
        ),
        migrations.AlterField(
            model_name='playerrating',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Screenshot of in-game rating', null=True, upload_to='rating_screenshots/'),
        ),
    ]
