# Generated by Django 5.2.13 on 2026-05-03 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_matchresult_screenshot_and_more'),
        ('teams', '0004_player_total_clean_sheets'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleanSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clean_sheet_records', to='teams.player')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clean_sheets', to='matches.matchresult')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ['team__name'],
                'unique_together': {('result', 'team')},
            },
        ),
    ]
