# Generated by Django 5.2.13 on 2026-05-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_cleansheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='minute',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='minute',
            field=models.PositiveIntegerField(blank=True, help_text='Minute of the goal (optional)', null=True),
        ),
    ]
