# Generated by Django 5.2.13 on 2026-05-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_alter_card_minute_alter_goal_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disputed', 'Disputed')], db_index=True, default='pending', max_length=20),
        ),
    ]
