# Generated by Django 5.2.13 on 2026-05-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_alter_matchresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='away_penalties',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='home_penalties',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='is_extra_time',
            field=models.BooleanField(default=False),
        ),
    ]
