# Generated by Django 5.2.13 on 2026-05-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_player_avg_rating_player_matches_played_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gaming_id',
            field=models.CharField(blank=True, help_text='PSN ID / Xbox Gamertag / Steam ID', max_length=100, unique=True),
        ),
    ]
