# Generated by Django 5.2.13 on 2026-05-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_player_gaming_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_clean_sheets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
