# Generated by Django 5.2.13 on 2026-05-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_player_total_clean_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo_no_bg',
            field=models.ImageField(blank=True, null=True, upload_to='player_photos_nobg/'),
        ),
    ]
