# Generated by Django 5.2.13 on 2026-05-06 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_player_photo_no_bg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='matches_played',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_goals',
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='fas fa-trophy', help_text="FontAwesome class, e.g. 'fas fa-trophy' or 'fas fa-medal'", max_length=50)),
                ('color', models.CharField(default='#d4af37', help_text="Hex color code, e.g. '#d4af37'", max_length=50)),
                ('category', models.CharField(choices=[('team', 'Team Trophy'), ('player', 'Player Badge')], max_length=10)),
                ('date_awarded', models.DateField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='teams.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to='teams.team')),
            ],
            options={
                'verbose_name_plural': 'Trophies',
                'ordering': ['-date_awarded'],
            },
        ),
    ]
