# Generated by Django 5.2.13 on 2026-05-06 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_remove_player_matches_played_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Market value of the player', max_digits=12),
        ),
        migrations.AddField(
            model_name='team',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total budget allocated to the team', max_digits=12),
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_from', to='teams.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.player')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_to', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_fee', models.DecimalField(decimal_places=2, default=0, help_text='Agreed transfer fee', max_digits=12)),
                ('current_captain_approved', models.BooleanField(default=False)),
                ('new_captain_approved', models.BooleanField(default=False)),
                ('admin_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CURRENT_CAPTAIN_APPROVED', 'Current Captain Approved'), ('NEW_CAPTAIN_APPROVED', 'New Captain Approved'), ('ADMIN_APPROVED', 'Admin Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='teams.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.player')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='teams.team')),
            ],
        ),
    ]
