# Generated by Django 5.2.13 on 2026-05-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_transferwindow_player_value_team_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='matches_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_assists',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_goals',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
