# Generated by Django 5.2.13 on 2026-05-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_player_matches_played_player_total_assists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='total_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=6),
        ),
    ]
