# Generated by Django 5.2.13 on 2026-05-20 11:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_player_total_rating'),
        ('tournaments', '0007_leaguestanding_playertournamentstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferhistory',
            options={'ordering': ['-transfer_date'], 'verbose_name_plural': 'Transfer histories'},
        ),
        migrations.AlterModelOptions(
            name='transferrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transferwindow',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='admin_approved',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='current_captain_approved',
        ),
        migrations.RemoveField(
            model_name='transferrequest',
            name='new_captain_approved',
        ),
        migrations.AddField(
            model_name='player',
            name='is_on_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_transfer_listed',
            field=models.BooleanField(default=False, help_text='Player is available on the transfer market'),
        ),
        migrations.AddField(
            model_name='player',
            name='loan_expires',
            field=models.DateField(blank=True, help_text='Date the loan period ends', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='parent_club',
            field=models.ForeignKey(blank=True, help_text='Original club if player is currently on loan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaned_out_players', to='teams.team'),
        ),
        migrations.AddField(
            model_name='transferhistory',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transferhistory',
            name='transfer_type',
            field=models.CharField(choices=[('permanent', 'Permanent Transfer'), ('loan', 'Loan'), ('free_agent', 'Free Agent')], default='permanent', max_length=20),
        ),
        migrations.AddField(
            model_name='transferhistory',
            name='window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='teams.transferwindow'),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='loan_end_date',
            field=models.DateField(blank=True, help_text='Required for loan transfers', null=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='transfer_type',
            field=models.CharField(choices=[('permanent', 'Permanent Transfer'), ('loan', 'Loan'), ('free_agent', 'Free Agent')], default='permanent', max_length=20),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='window',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='teams.transferwindow'),
        ),
        migrations.AddField(
            model_name='transferwindow',
            name='allowed_types',
            field=models.JSONField(blank=True, default=list, help_text='List of allowed transfer types, e.g. ["permanent", "loan", "free_agent"]. Empty = all allowed.'),
        ),
        migrations.AddField(
            model_name='transferwindow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferwindow',
            name='max_transfers_per_team',
            field=models.PositiveIntegerField(default=5, help_text='Maximum transfers a single team can make in this window.'),
        ),
        migrations.AddField(
            model_name='transferwindow',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='teams.player'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='teams.player'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Selling Club Approval'), ('SELLING_APPROVED', 'Selling Club Approved'), ('ADMIN_REVIEW', 'Awaiting Admin Review'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='transferwindow',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Manual override. Window is only open if active AND within date range.'),
        ),
        migrations.CreateModel(
            name='PlayerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible_from', models.DateField(help_text='Date from which the player is eligible to play')),
                ('is_active', models.BooleanField(default=True)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_registrations', to='tournaments.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='teams.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_registrations', to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('player', 'league', 'team')},
            },
        ),
    ]
