# Generated by Django 5.2.13 on 2026-05-21 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_alter_transferhistory_options_and_more'),
        ('teams', '0010_transfer_system_overhaul'),
    ]

    operations = [
    ]
