# Generated by Django 5.2.13 on 2026-04-30 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='tournament_banners/')),
                ('description', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True, help_text='Tournament rules and regulations')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('max_teams', models.PositiveIntegerField(default=16)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prize_pool', models.CharField(blank=True, max_length=200)),
                ('format', models.CharField(choices=[('round_robin', 'Round Robin'), ('knockout', 'Knockout'), ('group_knockout', 'Group Stage + Knockout')], default='round_robin', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('registration', 'Registration Open'), ('closed', 'Registration Closed'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('points_win', models.PositiveIntegerField(default=3)),
                ('points_draw', models.PositiveIntegerField(default=1)),
                ('points_loss', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_teams', models.PositiveIntegerField(default=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teams', models.ManyToManyField(blank=True, related_name='leagues', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.PositiveIntegerField(default=1)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='teams.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='teams.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='tournaments.league')),
            ],
            options={
                'ordering': ['matchday', 'created_at'],
            },
        ),
    ]
