# Generated by Django 5.2.13 on 2026-04-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='format',
        ),
        migrations.AddField(
            model_name='league',
            name='format',
            field=models.CharField(choices=[('round_robin', 'Round Robin (Single Leg)'), ('round_robin_2leg', 'Round Robin (2 Legs)'), ('group_stage', 'Group Stage'), ('knockout', 'Knockout'), ('group_knockout', 'Group Stage + Knockout')], default='round_robin', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
