# Generated by Django 5.2.13 on 2026-04-30 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_player_avg_rating_player_matches_played_and_more'),
        ('tournaments', '0002_remove_tournament_format_league_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_open',
            field=models.BooleanField(default=False, help_text='Allow teams to self-apply for this tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TournamentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('assigned_league', models.ForeignKey(blank=True, help_text='League assigned upon acceptance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='tournaments.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_applications', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('tournament', 'team')},
            },
        ),
    ]
