# Generated by Django 5.2.13 on 2026-05-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_fixture_matchday_alter_fixture_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='knockout_legs',
            field=models.PositiveIntegerField(choices=[(1, 'Single Leg'), (2, 'Two Legs')], default=1, help_text='Only applicable for Knockout format'),
        ),
    ]
