# Generated by Django 5.2.13 on 2026-05-11 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_player_total_rating'),
        ('tournaments', '0005_league_knockout_legs'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='bracket_index',
            field=models.PositiveIntegerField(blank=True, help_text='Position in the bracket for this round', null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='is_placeholder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fixture',
            name='next_fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_fixtures', to='tournaments.fixture'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='round_type',
            field=models.CharField(blank=True, choices=[('round_32', 'Round of 32'), ('round_16', 'Round of 16'), ('quarter_final', 'Quarter Final'), ('semi_final', 'Semi Final'), ('final', 'Final'), ('third_place', 'Third Place Match')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures_won', to='teams.team'),
        ),
        migrations.AddField(
            model_name='league',
            name='away_goals_rule',
            field=models.BooleanField(default=False, help_text='Enable away goals rule for two-legged ties'),
        ),
        migrations.AddField(
            model_name='league',
            name='third_place_match',
            field=models.BooleanField(default=False, help_text='Generate a third-place match for knockout tournaments'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='teams.team'),
        ),
    ]
