# Generated by Django 5.2.13 on 2026-05-11 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_player_total_rating'),
        ('tournaments', '0006_fixture_bracket_index_fixture_is_placeholder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveIntegerField(default=0)),
                ('won', models.PositiveIntegerField(default=0)),
                ('drawn', models.PositiveIntegerField(default=0)),
                ('lost', models.PositiveIntegerField(default=0)),
                ('gf', models.PositiveIntegerField(default=0, verbose_name='Goals For')),
                ('ga', models.PositiveIntegerField(default=0, verbose_name='Goals Against')),
                ('gd', models.IntegerField(default=0, verbose_name='Goal Difference')),
                ('points', models.PositiveIntegerField(default=0)),
                ('form', models.CharField(default='', help_text='Last 5 matches e.g. WLDWW', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computed_standings', to='tournaments.league')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ['-points', '-gd', '-gf'],
                'unique_together': {('league', 'team')},
            },
        ),
        migrations.CreateModel(
            name='PlayerTournamentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='tournaments.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_stats', to='teams.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ['-goals', '-assists'],
                'unique_together': {('league', 'player')},
            },
        ),
    ]
